name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: latest
          project_id: myprojectepa
          service_account_key: ${{ secrets.GCP_CI_SA_KEY }}
          export_default_credentials: true
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        env:
          GOOGLE_CLOUD_PROJECT: myprojectepa
        run: mvn --batch-mode --update-snapshots verify
      - name: MegaLinter
        id: ml
        # You can override MegaLinter flavor used to have faster performances
        # More info at https://megalinter.github.io/flavors/
        uses: megalinter/megalinter/flavors/java@v5