name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        env:
          GOOGLE_CLOUD_PROJECT: myprojectepa
          run: mvn --batch-mode --update-snapshots verify
    - id: 'deploy'
      name: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        deliverables: 'src/appengine/app.yaml'
        project_id: 'split-the-bill'
    - name: 'show output'
      run: 'echo ${{ steps.deploy.outputs.url }}'